package repository;

import com.mysql.cj.x.protobuf.MysqlxCrud;
import db.DbConn;
import domain.CleaningOrder;
import domain.Employee;
import domain.OrderStatus;
import domain.Room;

import java.sql.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.Optional;

/**
 * @author Simon Lundgren
 * @version 1.0
 * Created on: 2025-02-28
 */
public class CleaningOrderDao implements Dao<CleaningOrder> {

    PreparedStatement prst = null;

    DbConn dbConn;

    /**
     * Constructor with injectable database connection instance for mock testing.
     *
     * @param dbConn The database connection instance
     */
    public CleaningOrderDao(DbConn dbConn) {
        this.dbConn = dbConn;
    }

    /**
     * Constructor which retrieves an instance of the database connection.
     */
    public CleaningOrderDao() {
        this(DbConn.i());
    }

    /**
     * Creates a record from a temporary cleaning order object with an autogenerated id in the database,
     * and returns the same record with the generated id.
     *
     * @param cleaningOrder The cleaning order to be persisted
     * @return The same cleaning order with a generated id
     * @throws SQLException If a database error occurs
     */
    @Override
    public CleaningOrder save(CleaningOrder cleaningOrder) throws SQLException {
        if (cleaningOrder == null) {
            throw new IllegalArgumentException("The cleaningOrder cannot be null");
        }

        String query = "INSERT INTO lab_cleaning_orders(employee_id, room_id, time_scheduled, time_finished, order_status) " +
                "VALUES(?, ?, ?, ?, ?);";
        CleaningOrder cleaningOrderSaved = null;
        Timestamp timeFinished = cleaningOrder.getTimeFinished()
                .map(Timestamp::valueOf)
                .orElse(null);

        prst = dbConn.prepareStatement(query);
        prst.setInt(1, cleaningOrder.getEmployeeId());
        prst.setInt(2, cleaningOrder.getRoomId());
        prst.setTimestamp(3, Timestamp.valueOf(cleaningOrder.getTimeScheduled()));
        prst.setTimestamp(4, timeFinished);
        prst.setString(5, cleaningOrder.getOrderStatus().toString());
        prst.executeUpdate();

        ResultSet rs = prst.getGeneratedKeys();
        if (rs.next()) {
            int orderId = rs.getInt(1);
            cleaningOrderSaved = new CleaningOrder(
                    orderId,
                    cleaningOrder.getEmployeeId(),
                    cleaningOrder.getRoomId(),
                    cleaningOrder.getTimeScheduled(),
                    cleaningOrder.getTimeFinished().orElse(null),
                    cleaningOrder.getOrderStatus());
        }
        return cleaningOrderSaved;
    }

    /**
     * Updates mutable fields of a cleaning order in the database, matching the id of the passed order.
     *
     * @param cleaningOrder The cleaning order to update.
     * @return The updated cleaning order from the database
     * @throws SQLException If a database error occurs
     */
    @Override
    public CleaningOrder update(CleaningOrder cleaningOrder) throws SQLException {
        if (cleaningOrder == null) {
            throw new IllegalArgumentException("The cleaningOrder to update cannot be null");
        }

        String query = "UPDATE lab_cleaning_orders SET time_scheduled = ?, time_finished = ?, order_status = ? " +
                "WHERE id = ?;";
        prst = dbConn.prepareStatement(query);
        prst.setTimestamp(1, Timestamp.valueOf(cleaningOrder.getTimeScheduled()));
        prst.setTimestamp(2, Timestamp.valueOf(cleaningOrder.getTimeFinished().get()));
        prst.setString(3, cleaningOrder.getOrderStatus().toString());
        prst.setInt(4, cleaningOrder.getOrderId());
        return this.get(cleaningOrder.getOrderId()).orElseThrow();
    }

    /**
     * Deletes a cleaning order from the database, matching the id of the passed object.
     *
     * @param cleaningOrder The cleaning order to delet
     * @return true if successful, false otherwise
     * @throws SQLException If a database error occurs
     */
    @Override
    public boolean delete(CleaningOrder cleaningOrder) throws SQLException {
        if (cleaningOrder == null) {
            throw new IllegalArgumentException("The cleaningOrder to delete cannot be null");
        }

        String query = "DELETE FROM lab_cleaning_orders WHERE id = ?;";
        prst = dbConn.prepareStatement(query);
        prst.setInt(1, cleaningOrder.getOrderId());
        int affectedRows = prst.executeUpdate();
        int expectedAffectedRows = 1;
        return affectedRows == expectedAffectedRows;
    }

    /**
     * Retrieves a cleaning order record from the database, matching the passed id. The cleaning order
     * will only contain the id's of the room and employee it pertains, not the full objects.
     *
     * @param id The id of the cleaning order to retrieve
     * @return The Cleaning Order
     * @throws SQLException If a database error occurs
     */
    @Override
    public Optional<CleaningOrder> get(int id) throws SQLException {
        if (id < 0) {
            throw new IllegalArgumentException("Id cannot be negative");
        }

        String query = "SELECT id, employee_id, room_id, time_scheduled, time_finished, order_status FROM " +
                "lab_cleaning_orders WHERE id = ?;";
        prst = dbConn.prepareStatement(query);
        prst.setInt(1, id);
        ResultSet rs = prst.executeQuery();
        CleaningOrder cleaningOrder = null;
        if (rs.next()) {
            int orderId = rs.getInt("id");
            int employeeId = rs.getInt("employee_id");
            int roomId = rs.getInt("room_id");
            LocalDateTime timeScheduled = rs.getTimestamp("time_scheduled").toLocalDateTime();
            LocalDateTime timeFinished = null;
            OrderStatus orderStatus = OrderStatus.valueOf(rs.getString("order_status"));

            Timestamp timestampFinished = rs.getTimestamp("time_finished");
            if (timestampFinished != null) {
                timeFinished = timestampFinished.toLocalDateTime();
            }
            cleaningOrder = new CleaningOrder(orderId, employeeId, roomId, timeScheduled, timeFinished, orderStatus);
        }
        return Optional.ofNullable(cleaningOrder);
    }

    /**
     * Retrieves all the cleaning orders records in the database.
     *
     * @return A list of all cleaning orders in the database
     * @throws SQLException If a database error occurs
     */
    @Override
    public List<CleaningOrder> getAll() throws SQLException {
        String query = "SELECT id, employee_id, room_id, time_scheduled, time_finished, order_status FROM " +
                "lab_cleaning_orders;";
        prst = dbConn.prepareStatement(query);
        ResultSet rs = prst.executeQuery();
        List<CleaningOrder> cleaningOrders = new ArrayList<>();
        while (rs.next()) {
            int orderId = rs.getInt("id");
            int employeeId = rs.getInt("employee_id");
            int roomId = rs.getInt("room_id");
            LocalDateTime timeScheduled = rs.getTimestamp("time_scheduled").toLocalDateTime();
            LocalDateTime timeFinished = null;
            OrderStatus orderStatus = OrderStatus.valueOf(rs.getString("order_status"));

            Timestamp timestampFinished = rs.getTimestamp("time_finished");
            if (timestampFinished != null) {
                timeFinished = timestampFinished.toLocalDateTime();
            }

            CleaningOrder cleaningOrder = new CleaningOrder(orderId, employeeId, roomId, timeScheduled, timeFinished, orderStatus);
            cleaningOrders.add(cleaningOrder);
        }
        return cleaningOrders;
    }

    /**
     * Retrieves all cleaning orders associated with the passed employee id.
     *
     * @param employeeId The employee id
     * @return A list of cleaning orders assigned to the employee
     * @throws SQLException if a database error occurs
     */
    public List<CleaningOrder> getAllByEmployee(int employeeId) throws SQLException {
        if (employeeId <= 0) {
            throw new IllegalArgumentException("employeeId cannot be zero or negative");
        }

        String query = "SELECT id, employee_id, room_id, time_scheduled, time_finished, order_status " +
                "FROM lab_cleaning_orders WHERE employee_id = ?;";
        prst = dbConn.prepareStatement(query);
        prst.setInt(1, employeeId);
        List<CleaningOrder> cleaningOrders = new ArrayList<>();
        ResultSet rs = prst.executeQuery();
        while (rs.next()) {
            int orderId = rs.getInt("id");
            employeeId = rs.getInt("employee_id");
            int roomId = rs.getInt("room_id");
            LocalDateTime timeScheduled = rs.getTimestamp("time_scheduled").toLocalDateTime();
            LocalDateTime timeFinished = null;
            OrderStatus orderStatus = OrderStatus.valueOf(rs.getString("order_status"));

            Timestamp timestampFinished = rs.getTimestamp("time_finished");
            if (timestampFinished != null) {
                timeFinished = timestampFinished.toLocalDateTime();
            }

            CleaningOrder cleaningOrder = new CleaningOrder(orderId, employeeId, roomId, timeScheduled, timeFinished, orderStatus);
            cleaningOrders.add(cleaningOrder);
        }
        return cleaningOrders;
    }

    /**
     * Retrieves all cleaning orders associated with the passed employee.
     *
     * @param employee The employee
     * @return A list of cleaning orders assigned to the employee
     * @throws SQLException if a database error occurs
     */
    public List<CleaningOrder> getAllByEmployee(Employee employee) throws SQLException {
        if (employee == null) {
            throw new IllegalArgumentException("Employee cannot be null");
        }
        return getAllByEmployee(employee.getId());
    }

    /**
     * Retrieves all cleaning orders associated with the passed room id.
     *
     * @param roomId The employee id
     * @return A list of cleaning orders assigned to the room
     * @throws SQLException if a database error occurs
     */
    public List<CleaningOrder> getAllByRoom(int roomId) throws SQLException {
        if (roomId <= 0) {
            throw new IllegalArgumentException("roomId cannot be zero or negative");
        }

        String query = "SELECT id, employee_id, room_id, time_scheduled, time_finished, order_status " +
                "FROM lab_cleaning_orders WHERE room_id = ?;";
        prst = dbConn.prepareStatement(query);
        prst.setInt(1, roomId);
        List<CleaningOrder> cleaningOrders = new ArrayList<>();
        ResultSet rs = prst.executeQuery();
        while (rs.next()) {
            int orderId = rs.getInt("id");
            int employeeId = rs.getInt("employee_id");
            roomId = rs.getInt("room_id");
            LocalDateTime timeScheduled = rs.getTimestamp("time_scheduled").toLocalDateTime();
            LocalDateTime timeFinished = null;
            OrderStatus orderStatus = OrderStatus.valueOf(rs.getString("order_status"));

            Timestamp timestampFinished = rs.getTimestamp("time_finished");
            if (timestampFinished != null) {
                timeFinished = timestampFinished.toLocalDateTime();
            }

            CleaningOrder cleaningOrder = new CleaningOrder(orderId, employeeId, roomId, timeScheduled, timeFinished, orderStatus);
            cleaningOrders.add(cleaningOrder);
        }
        return cleaningOrders;
    }

    /**
     * Retrieves all cleaning orders associated with the passed room id.
     *
     * @return A list of cleaning orders assigned to the room
     * @throws SQLException if a database error occurs
     */
    public List<CleaningOrder> getAllByRoom(Room room) throws SQLException {
        if (room == null) {
            throw new IllegalArgumentException("Room cannot be null");
        }
        return this.getAllByRoom(room.getId());
    }
}
