package repository;

import db.DbConn;
import domain.Room;
import domain.Site;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.NoSuchElementException;

/**
 * A DAO class for retrieving and persisting Site records in the database.
 */
public class SiteDao implements Dao<Site> {

    private PreparedStatement prst = null;

    /**
     * Creates a record from a temporary Site object with an autogenerated id in the database, and returns
     * the same record with the generated id.
     *
     * @param site The object to save
     * @return The same object with a generated id
     */
    @Override
    public Site save(Site site) {
        String query = "INSERT INTO lab_sites(name, address, postal_code, postal_area, property_designation) " +
                "VALUES(?, ?, ?, ?, ?)";
        Site siteSaved = null;
        try {
            prst = DbConn.i().prepareStatement(query);
            prst.setString(1, site.getName());
            prst.setString(2, site.getAddress());
            prst.setInt(3, site.getPostalCode());
            prst.setString(4, site.getPostalArea());
            prst.setString(5, site.getPropertyDesignation());
            prst.executeUpdate();

            ResultSet rs = prst.getGeneratedKeys();
            if (rs.next()) {
                int newId = rs.getInt(1);
                siteSaved = new Site(newId,
                        site.getName(),
                        site.getAddress(),
                        site.getPostalCode(),
                        site.getPostalArea(),
                        site.getPropertyDesignation(),
                        site.getRooms());
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return siteSaved;
    }

    /**
     * Updates mutable fields of a site in the database matching the id of the passed site object.
     *
     * @param siteToUpdate The site to update
     * @return True if successful, false otherwise.
     */
    @Override
    public boolean update(Site siteToUpdate) {
        String query = "UPDATE lab_sites SET name = ? WHERE id = ?";
        try {
            prst = DbConn.i().prepareStatement(query);
            prst.setString(1, siteToUpdate.getName());
            prst.setInt(2, siteToUpdate.getId());
            int affectedRows = prst.executeUpdate();
            int expectedAffectedRows = 1;
            if (affectedRows == expectedAffectedRows) {
                return true;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }

    /**
     * Deletes a Site record from the database which matches the passed site objects id. This will cascade
     * to all Rooms that are bound to the site in the database.
     *
     * @param siteToDelete The site to delete
     * @return True if successful, false otherwise
     */
    @Override
    public boolean delete(Site siteToDelete) {
        String query = "DELETE FROM lab_sites WHERE id = ?";
        try {
            prst = DbConn.i().prepareStatement(query);
            prst.setInt(1, siteToDelete.getId());
            int affectedRows = prst.executeUpdate();
            int expectedAffectedRows = 1;
            if (affectedRows == expectedAffectedRows) {
                return true;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }

    /**
     * Retrieves a site record from the database matching the passed id. The Site object will also contain
     * a list of all room records associated with the site.
     *
     * @param id The primary key of the site
     * @return The Site record matching the passed id.
     * @throws NoSuchElementException If there is not matching id in the database
     */
    @Override
    public Site get(int id) {
        String query = "SELECT id, name, address, postal_code, postal_area, property_designation FROM lab_sites " +
                "WHERE id = ?";
        Site fetchedSite = null;
        try {
            prst = DbConn.i().prepareStatement(query);
            prst.setInt(1, id);
            prst.executeQuery();
            ResultSet rs = prst.getResultSet();
            if (rs.next()) {
                String name = rs.getString("name");
                String address = rs.getString("address");
                int postalCode = rs.getInt("postal_code");
                String postalArea = rs.getString("postal_area");
                String propertyDesignation = rs.getString("property_designation");
                List<Room> roomsOnSite = new RoomDao().getAllRoomsOnSite(id);
                fetchedSite = new Site(id, name, address, postalCode, postalArea, propertyDesignation, roomsOnSite);
            } else {
                String errorMessage = String.format("A site with ID: %d does not exist in the database!", id);
                throw new NoSuchElementException(errorMessage);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return fetchedSite;
    }

    /**
     * Retrieves all site records from the database.
     *
     * @return A list of all Site objects in the database.
     */
    @Override
    public List<Site> getAll() {
        String query = "SELECT id, name, address, postal_code, postal_area, property_designation FROM lab_sites";
        List<Site> fetchedSites = new ArrayList<>();
        RoomDao roomDao = new RoomDao();
        try {
            prst = DbConn.i().prepareStatement(query);
            prst.executeQuery();
            ResultSet rs = prst.getResultSet();
            while (rs.next()) {
                int siteId = rs.getInt("id");
                String name = rs.getString("name");
                String address = rs.getString("address");
                int postalCode = rs.getInt("postal_code");
                String postalArea = rs.getString("postal_area");
                String propertyDesignation = rs.getString("property_designation");
                List<Room> roomsOnSite = roomDao.getAllRoomsOnSite(siteId);
                fetchedSites.add(new Site(siteId, name, address, postalCode, postalArea, propertyDesignation, roomsOnSite));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return fetchedSites;
    }

}
