package repository;

import db.DatabaseConnector;
import db.DbConn;
import domain.Room;
import domain.Site;
import service.logger.Logger;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.Optional;

/**
 * A DAO class for retrieving and persisting Site records in the database.
 *
 * @author Simon Lundgren
 * @version 1.0
 */
public class SiteDao extends BaseDao<Site> {

    private PreparedStatement prst = null;

    private static final Logger LOGGER = Logger.get(SiteDao.class);

    /**
     * Constructor with injectable database connection instance.
     *
     * @param dbConn The database connection instance
     */
    public SiteDao(DatabaseConnector dbConn) {
        super(dbConn);
    }

    /**
     * Constructor which retrieves an instance of the database connection.
     */
    public SiteDao() {
        super();
    }

    /**
     * Creates a record from a temporary Site object with an autogenerated id in the database, and returns
     * the same record with the generated id.
     *
     * @param site The object to save
     * @return The same object with a generated id
     */
    @Override
    public Site save(Site site) throws SQLException {
        if (site == null) {
            throw new IllegalArgumentException("Site cannot be null");
        }

        String query = "INSERT INTO lab_sites(name, address, postal_code, postal_area, property_designation) " +
                "VALUES(?, ?, ?, ?, ?)";
        Site siteSaved = null;
        prst = DbConn.i().prepareStatement(query);
        prst.setString(1, site.getName());
        prst.setString(2, site.getAddress());
        prst.setInt(3, site.getPostalCode());
        prst.setString(4, site.getPostalArea());
        prst.setString(5, site.getPropertyDesignation());
        prst.execute();

        ResultSet rs = prst.getGeneratedKeys();
        if (rs.next()) {
            int newId = rs.getInt(1);
            siteSaved = new Site(newId,
                    site.getName(),
                    site.getAddress(),
                    site.getPostalCode(),
                    site.getPostalArea(),
                    site.getPropertyDesignation(),
                    new RoomDao().getAllRoomsOnSite(newId));
            LOGGER.info(() -> String.format("Site successfully saved to database: %s, Id %d", site.getName(), site.getId()));
        }
        return siteSaved;
    }

    /**
     * Updates mutable fields of a site in the database matching the id of the passed site object.
     *
     * @param site The site to update
     * @return The updated site from the database
     */
    @Override
    public Site update(Site site) throws SQLException {
        if (site == null) {
            throw new IllegalArgumentException("Site cannot be null");
        }

        String query = "UPDATE lab_sites SET name = ? WHERE id = ?";
        prst = DbConn.i().prepareStatement(query);
        prst.setString(1, site.getName());
        prst.setInt(2, site.getId());
        prst.executeUpdate();
        Site siteUpdated = get(site.getId()).orElseThrow();
        LOGGER.info(() -> String.format("Site successfully updated: %s, %d", siteUpdated.getName(), site.getId()));
        return siteUpdated;
    }

    /**
     * Deletes a Site record from the database which matches the passed site objects id. This will cascade
     * to all Rooms that are bound to the site in the database.
     *
     * @param site The site to delete
     * @return True if successful, false otherwise
     */
    @Override
    public boolean delete(Site site) throws SQLException {
        if (site == null) {
            throw new IllegalArgumentException("Site cannot be null");
        }

        String query = "DELETE FROM lab_sites WHERE id = ?";
        prst = DbConn.i().prepareStatement(query);
        prst.setInt(1, site.getId());
        int affectedRows = prst.executeUpdate();
        int expectedAffectedRows = 1;
        if (affectedRows == expectedAffectedRows) {
            LOGGER.info(() -> String.format("Site successfully deleted: %s, id %d", site.getName(), site.getId()));
            return true;
        }
        LOGGER.info(() -> String.format("Failed to delete site: %s, id %d", site.getName(), site.getId()));
        return false;
    }

    /**
     * Retrieves a site record from the database matching the passed id. The Site object will also contain
     * a list of all room records associated with the site.
     *
     * @param id The primary key of the site
     * @return The Site record matching the passed id.
     * @throws NoSuchElementException If there is not matching id in the database
     */
    @Override
    public Optional<Site> get(int id) throws SQLException {
        if (id <= 0) {
            throw new IllegalArgumentException("Site id cannot be zero or negative.");
        }

        Site site = null;
        String query = "SELECT id, name, address, postal_code, postal_area, property_designation FROM lab_sites " +
                "WHERE id = ?";
        prst = DbConn.i().prepareStatement(query);
        prst.setInt(1, id);
        prst.executeQuery();
        ResultSet rs = prst.getResultSet();
        if (rs.next()) {
            site = mapResultSetToEntity(rs);
            String logMessage = String.format("Site successfully retrieved: %s, Id %d", site.getName(), site.getId());
            LOGGER.info(() -> logMessage);
        }
        return Optional.ofNullable(site);
    }

    /**
     * Retrieves all site records from the database.
     *
     * @return A list of all Site objects in the database.
     */
    @Override
    public List<Site> getAll() throws SQLException {
        String query = "SELECT id, name, address, postal_code, postal_area, property_designation FROM lab_sites";
        List<Site> fetchedSites = new ArrayList<>();
        prst = DbConn.i().prepareStatement(query);
        prst.executeQuery();
        ResultSet rs = prst.getResultSet();
        while (rs.next()) {
            fetchedSites.add(mapResultSetToEntity(rs));
        }
        return fetchedSites;
    }

    public List<Site> getAllSiteWithRoomsInit() throws SQLException {
        String query = "SELECT id, name, address, postal_code, postal_area, property_designation FROM lab_sites";
        List<Site> fetchedSites = new ArrayList<>();
        RoomDao roomDao = new RoomDao();
        prst = DbConn.i().prepareStatement(query);
        prst.executeQuery();
        ResultSet rs = prst.getResultSet();
        while (rs.next()) {
            int siteId = rs.getInt("id");
            String name = rs.getString("name");
            String address = rs.getString("address");
            int postalCode = rs.getInt("postal_code");
            String postalArea = rs.getString("postal_area");
            String propertyDesignation = rs.getString("property_designation");
            List<Room> roomsOnSite = roomDao.getAllRoomsOnSite(siteId);
            fetchedSites.add(new Site(siteId, name, address, postalCode, postalArea, propertyDesignation, roomsOnSite));
        }
        return fetchedSites;
    }

    /**
     * Checks if a site with the passed id exists in the database.
     *
     * @param id the Site id
     * @return true if present, false otherwise
     */
    public boolean existsById(int id) throws SQLException {
        if (id <= 0) {
            throw new IllegalArgumentException("Id cannot be zero or negative");
        }

        String query = "SELECT EXISTS(SELECT 1 FROM lab_sites WHERE id = ?)";
        prst = dbConn.prepareStatement(query);
        prst.setInt(1, id);
        prst.executeQuery();
        ResultSet rs = prst.getResultSet();
        if (rs.next()) {
            return rs.getBoolean(1);
        } else {
            return false;
        }
    }

    @Override
    protected Site mapResultSetToEntity(ResultSet resultSet) throws SQLException {
        int id = resultSet.getInt("id");
        String name = resultSet.getString("name");
        String address = resultSet.getString("address");
        int postalCode = resultSet.getInt("postal_code");
        String postalArea = resultSet.getString("postal_area");
        String propertyDesignation = resultSet.getString("property_designation");
        List<Room> roomsOnSite = new RoomDao().getAllRoomsOnSite(id);
        return new Site(id, name, address, postalCode, postalArea, propertyDesignation, roomsOnSite);
    }
}