package domain;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * A class representing a physical site to perform cleaning work at, for the purpose of a cleaning management
 * system.
 *
 * <p>This class provides basic fields for a site's name, address and property designation, as well as database id,
 * meant to represent a real estate or property. It also provides a list of {@code Room}, that are associated
 * with this site. The Room list should only be injected in retrieval from the database to ensure proper foreign key matches.
 * When insertion into the database, the room list should be empty.</p>
 *
 * <p>All fields except the name have their setters set to private, as they are not expected to change after instantiation or
 * insertion into the database. </p>
 *
 * @author Simon Lundgren
 */
public class Site {

    private int id;
    private String name;
    private String address;
    private int postalCode;
    private String postalArea;
    private String propertyDesignation;

    private List<Room> rooms;

    /**
     * A Site object created using the non-id constructor (before insertion into a database) will receive
     * this id as default.
     */
    private static final int NO_ID = 0;

    /**
     * Constructor for retrieving a site record from the database with a generated id.
     *
     * @param id                  The id, autogenerated by the database
     * @param name                The name of the site, optional
     * @param address             The address of the site, non-null, max 100 characters
     * @param postalCode          The postal code, Swedish standard (1xxxx-9xxxx). Non-null.
     * @param postalArea          The geographical postal location
     * @param propertyDesignation The land property designation, as defined by Lantmäteriet
     *                            (ex: GÄVLE VÄSTER 10:5). Non-null, max 50 characters.
     * @param rooms               A list of Room objects which the site contains
     */
    public Site(int id,
                String name,
                String address,
                int postalCode,
                String postalArea,
                String propertyDesignation,
                List<Room> rooms) {
        setId(id);
        setName(name);
        setAddress(address);
        setPostalCode(postalCode);
        setPostalArea(postalArea);
        setPropertyDesignation(propertyDesignation);
        setRooms(rooms);
    }

    /**
     * Constructor for creating a site object for insertion into a database, where an id will be generated. The list
     * of rooms is set to null.
     *
     * @param name                The name of the site, optional
     * @param address             The address of the site, non-null, max 100 characters
     * @param postalCode          The postal code, Swedish standard (1xxxx-9xxxx). Non-null.
     * @param postalArea          The geographical postal location
     * @param propertyDesignation The land property designation, as defined by Lantmäteriet
     *                            (ex: GÄVLE VÄSTER 10:5). Non-null, max 50 characters.
     */
    public Site(String name,
                String address,
                int postalCode,
                String postalArea,
                String propertyDesignation) {
        this(NO_ID, name, address, postalCode, postalArea, propertyDesignation, null);
    }

    private void setId(int id) {
        if (id < 0) {
            throw new IllegalArgumentException("Id cannot be a negative number!");
        }
        this.id = id;
    }

    public void setName(String name) {
        if (name == null || name.isEmpty()) {
            this.name = null;
        } else if (name.length() > 100) {
            throw new IllegalArgumentException("Name cannot be longer than 100 characters!");
        } else {
            this.name = name;
        }
    }

    private void setAddress(String address) {
        if (address == null || address.isEmpty()) {
            throw new IllegalArgumentException("Address cannot be empty or null!");
        }
        if (address.length() > 100) {
            throw new IllegalArgumentException("The address field cannot be longer than 100 characters!");
        }
        this.address = address;
    }

    private void setPostalCode(int postalCode) {
        if (postalCode < 10000 || postalCode > 99999) {
            throw new IllegalArgumentException("Invalid postal code! Must be between 10000-99999.");
        }
        this.postalCode = postalCode;
    }

    private void setPostalArea(String postalArea) {
        if (postalArea == null || postalArea.isEmpty()) {
            throw new IllegalArgumentException("The postal area field cannot be empty or null!");
        }
        if (postalArea.length() > 50) {
            throw new IllegalArgumentException("The postal area field cannot be longer than 50 characters!");
        }
        this.postalArea = postalArea;
    }

    private void setPropertyDesignation(String propertyDesignation) {
        if (propertyDesignation == null || propertyDesignation.isEmpty()) {
            throw new IllegalArgumentException("Property designation cannot be empty or null!");
        }
        if (propertyDesignation.length() > 50) {
            throw new IllegalArgumentException("Property designation cannot be longer than 50 characters!");
        }
        this.propertyDesignation = propertyDesignation;
    }

    private void setRooms(List<Room> rooms) {
        if (rooms == null) {
            // Create empty list if null.
            this.rooms = new ArrayList<Room>();
        } else {
            this.rooms = rooms;
        }
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getAddress() {
        return address;
    }

    public int getPostalCode() {
        return postalCode;
    }

    public String getPostalArea() {
        return postalArea;
    }

    public String getPropertyDesignation() {
        return propertyDesignation;
    }

    public List<Room> getRooms() {
        return rooms;
    }

    @Override
    public String toString() {
        return String.format("ID: %d, Name: %s, Address: %s, Postal Code: %s, Postal Area: %s, Property Designation: %s, Rooms: %d",
                getId(), getName(), getAddress(), getPostalCode(), getPostalArea(), getPropertyDesignation(), getRooms().size());
    }

    @Override
    public boolean equals(Object o) {
        if (o == null) return false;
        if (o == this) return true;
        if (o.getClass() != this.getClass()) return false;

        Site that = (Site) o;
        return this.id == that.getId() &&
                this.name.equals(that.getName()) &&
                this.address.equals(that.getAddress()) &&
                this.postalCode == that.getPostalCode() &&
                this.postalArea.equals(that.getPostalArea()) &&
                this.propertyDesignation.equals(that.getPropertyDesignation());
    }

    @Override
    public int hashCode() {
        // rooms field excluded from hash computation to avoid issues with potential lazy init later
        return Objects.hash(id, name, address, postalCode, postalArea, propertyDesignation);
    }

}
